[platformio]
default_envs = platform

;BRIDGE ESP32 
[env:bridge]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 460800
build_src_filter = +<bridge/*>

; PLATFORM ESP32 
[env:platform]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 460800
build_src_filter = +<platform/*>

lib_deps = 
    sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.3.2